clear; clc;
tic

% =========================================================================
% BF_test.m
% Tests the Bloom Filter loaded from bloomFilterNBA.mat.
% Checks for false negatives, measures empirical false positive rate,
% and plots false positive rate vs number of hash functions (k).
%
% Requires: data/processed/bloomFilterNBA.mat (generated by BF_populate.m)
% =========================================================================

scriptDir  = fileparts(mfilename('fullpath'));
projectDir = scriptDir;

while ~isfolder(fullfile(projectDir, "data", "processed")) && ...
      ~strcmp(projectDir, fileparts(projectDir))
    projectDir = fileparts(projectDir);
end

addpath(fullfile(projectDir, "scripts", "BF"));

filterPath = fullfile(projectDir, "data", "processed", "bloomFilterNBA.mat");

if ~isfile(filterPath)
    fprintf("Filter not found. Running BF_populate.m...\n\n");
    run(fullfile(projectDir, "scripts", "BF", "BF_populate.m"));
end

% redefine filterPath in case it was cleared by run()
filterPath = fullfile(projectDir, "data", "processed", "bloomFilterNBA.mat");

load(filterPath, "bf", "bloomKeys", "array_size", "nEntries");

%% TEST 1: false negatives
% Every key inserted must be found — a false negative is a critical bug
fprintf("=== Test 1: False negatives ===\n");

falseNegatives = 0;

for i = 1:nEntries
    if ~bf.exists(bloomKeys(i))
        falseNegatives = falseNegatives + 1;
        fprintf("[ERROR] '%s' not found (false negative!)\n", bloomKeys(i));
    end
end

if falseNegatives == 0
    fprintf("[OK] No false negatives found (%d keys tested)\n", nEntries);
else
    fprintf("[FAIL] %d false negatives found!\n", falseNegatives);
end

%% TEST 2: membership queries
% Players that should NOT be in the filter (post-1999 players)
fprintf("\n=== Test 2: Membership queries ===\n");

testAbsent = [
    "lebron james_2003_cle";
    "stephen curry_2010_gsw";
    "kevin durant_2007_okc";
];

for i = 1:length(testAbsent)
    key = testAbsent(i);
    if ~bf.exists(key)
        fprintf("[OK] '%s' not found (expected)\n", key);
    else
        fprintf("[FP] '%s' reported as present (false positive)\n", key);
    end
end

%% TEST 3: empirical false positive rate
fprintf("\n=== Test 3: Empirical false positive rate ===\n");

nTests  = 1000;
fpCount = 0;

rng(42);
for i = 1:nTests
    fakeKey = "fake_player_" + string(randi(1e9)) + "_" + string(randi(100));
    if bf.exists(fakeKey)
        fpCount = fpCount + 1;
    end
end

empiricalFP   = fpCount / nTests * 100;
theoreticalFP = bf.falsePositiveRate() * 100;

fprintf("Tests run             : %d\n",     nTests);
fprintf("False positives       : %d\n",     fpCount);
fprintf("Empirical FP rate     : %.4f%%\n", empiricalFP);
fprintf("Theoretical FP rate   : %.4f%%\n", theoreticalFP);

%% TEST 4: false positive rate vs k
% Reproduces the analysis from the course guide (PL6, exercise 4)
fprintf("\n=== Test 4: False positive rate vs k ===\n");
fprintf("%-5s  %-12s  %-12s  %-12s\n", "k", "Empirical", "Theoretical", "Active bits");

kValues   = 1:8;
empFPvec  = zeros(1, length(kValues));
theoFPvec = zeros(1, length(kValues));
rng(42);

for ki = 1:length(kValues)
    k   = kValues(ki);
    bfK = BloomFilter(array_size, k);
    for i = 1:nEntries
        bfK = bfK.add(bloomKeys(i));
    end

    fpK = 0;
    for i = 1:nTests
        fakeKey = "fake_player_" + string(randi(1e9)) + "_" + string(randi(100));
        if bfK.exists(fakeKey)
            fpK = fpK + 1;
        end
    end

    empFPvec(ki)  = fpK / nTests * 100;
    theoFPvec(ki) = bfK.falsePositiveRate() * 100;
    active        = sum(bfK.bits) / array_size * 100;

    fprintf("k=%-3d  %8.4f%%    %8.4f%%    %8.1f%%\n", k, empFPvec(ki), theoFPvec(ki), active);
end

%% PLOT: false positive rate vs k
figure;
plot(kValues, empFPvec,  'b-o', 'LineWidth', 2, 'MarkerFaceColor', 'b'); hold on;
plot(kValues, theoFPvec, 'r--s', 'LineWidth', 2, 'MarkerFaceColor', 'r');
xlabel('Number of hash functions (k)');
ylabel('False positive rate (%)');
title('Bloom Filter — False Positive Rate vs k (NBA dataset, n=38140)');
legend('Empirical', 'Theoretical');
grid on;
xticks(kValues);

[~, bestKi] = min(empFPvec);
xline(kValues(bestKi), '--g', sprintf('optimal k=%d', kValues(bestKi)), ...
    'LabelVerticalAlignment', 'bottom', 'LineWidth', 1.5);

plotPath = fullfile(projectDir, "data", "processed", "bf_fp_vs_k.png");
saveas(gcf, plotPath);
fprintf("\nPlot saved to: %s\n", plotPath);

toc