function [playerTags, tagLimits, statNames] = NBA_generateAllTags(statsMatrix)

    statNames = ["points", ...
                 "rebounds", ...
                 "assists", ...
                 "steals", ...
                 "blocks", ...
                 "fg", ...
                 "three_point", ...
                 "three_attempts", ...
                 "two_point", ...
                 "ft"];

    tagLimits = NBA_getTagLimits(statsMatrix, statNames);

    nPlayers = size(statsMatrix, 1);
    playerTags = cell(nPlayers, 1);

    for i = 1:nPlayers
        playerTags{i} = NBA_statsToTags(statsMatrix(i, :), tagLimits, statNames);
    end

end