function NBA_interface()
% =========================================================================
% NBA_interface.m
% NBA Time Machine — graphical interface
% =========================================================================

scriptDir  = fileparts(mfilename('fullpath'));
projectDir = scriptDir;
while ~isfolder(fullfile(projectDir, "data", "processed")) && ...
      ~strcmp(projectDir, fileparts(projectDir))
    projectDir = fileparts(projectDir);
end

addpath(fullfile(projectDir, "scripts", "BF"));
addpath(fullfile(projectDir, "scripts", "NB"));
addpath(fullfile(projectDir, "scripts", "MinHash"));
addpath(fullfile(projectDir, "scripts", "GeneralFuncs"));
addpath(fullfile(projectDir, "scripts"));

%% WINDOW
W = 900;
H = 580;

win = uifigure('Name', 'NBA Time Machine', ...
'Position', [200, 100, W, H], ...
    'Color', [0.13, 0.13, 0.20], ...
    'Resize', 'off');

%% HEADER
header = uipanel(win, ...
    'Position', [0, H-60, W, 60], ...
    'BackgroundColor', [0.10, 0.10, 0.16], ...
    'BorderType', 'none');

uiimage(header, ...
    'ImageSource', fullfile(projectDir, 'assets', 'basketball.png'), ...
    'Position', [15, 10, 40, 40]);

uilabel(header, ...
    'Text', 'NBA Time Machine', ...
    'Position', [65, 28, 400, 24], ...
    'FontSize', 18, 'FontWeight', 'bold', ...
    'FontColor', [1, 1, 1]);

uilabel(header, ...
    'Text', 'Find your 90s NBA twin', ...
    'Position', [65, 10, 400, 18], ...
    'FontSize', 12, ...
    'FontColor', [0.6, 0.6, 0.7]);

%% LEFT PANEL - input
leftPanel = uipanel(win, ...
    'Position', [15, 15, 400, H-80], ...
    'BackgroundColor', [0.16, 0.16, 0.24], ...
    'BorderType', 'line', ...
    'BorderWidth', 1, ...
    'HighlightColor', [0.25, 0.25, 0.38]);

uilabel(leftPanel, ...
    'Text', 'PLAYER INPUT', ...
    'Position', [15, leftPanel.Position(4)-35, 200, 20], ...
    'FontSize', 10, 'FontWeight', 'bold', ...
    'FontColor', [0.92, 0.27, 0.38]);

uilabel(leftPanel, 'Text', 'Player name', ...
    'Position', [15, leftPanel.Position(4)-65, 200, 16], ...
    'FontSize', 11, 'FontColor', [0.75, 0.75, 0.85]);

nameField = uieditfield(leftPanel, 'text', ...
    'Position', [15, leftPanel.Position(4)-95, 370, 28], ...
    'Value', 'LeBron James', ...
    'FontSize', 12, ...
    'BackgroundColor', [0.10, 0.14, 0.26], ...
    'FontColor', [1, 1, 1]);

uilabel(leftPanel, 'Text', 'Season year', ...
    'Position', [15, leftPanel.Position(4)-130, 200, 16], ...
    'FontSize', 11, 'FontColor', [0.75, 0.75, 0.85]);

yearField = uieditfield(leftPanel, 'numeric', ...
    'Position', [15, leftPanel.Position(4)-160, 160, 28], ...
    'Value', 2024, ...
    'FontSize', 12, ...
    'BackgroundColor', [0.10, 0.14, 0.26], ...
    'FontColor', [1, 1, 1]);

uilabel(leftPanel, 'Text', 'Team', ...
    'Position', [185, leftPanel.Position(4)-130, 200, 16], ...
    'FontSize', 11, 'FontColor', [0.75, 0.75, 0.85]);

teamField = uieditfield(leftPanel, 'text', ...
    'Position', [185, leftPanel.Position(4)-160, 170, 28], ...
    'Value', 'LAL', ...
    'FontSize', 12, ...
    'BackgroundColor', [0.10, 0.14, 0.26], ...
    'FontColor', [1, 1, 1]);

uilabel(leftPanel, 'Text', 'Season stats (per game)', ...
    'Position', [15, leftPanel.Position(4)-190, 300, 16], ...
    'FontSize', 11, 'FontColor', [0.75, 0.75, 0.85]);

statLabels  = {'PTS', 'TRB', 'AST', 'STL', 'BLK'};
statDefaults = [25.7, 7.3, 8.3, 1.3, 0.6];
statFields  = cell(1, 5);
colW = 64; colGap = 10;

for i = 1:5
    x = 15 + (i-1) * (colW + colGap);
    y = leftPanel.Position(4) - 230;
    uilabel(leftPanel, 'Text', statLabels{i}, ...
        'Position', [x, y+32, colW, 14], ...
        'FontSize', 10, 'FontWeight', 'bold', ...
        'FontColor', [0.6, 0.6, 0.75], ...
        'HorizontalAlignment', 'center');
    statFields{i} = uieditfield(leftPanel, 'numeric', ...
        'Position', [x, y, colW, 32], ...
        'Value', statDefaults(i), ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.10, 0.14, 0.26], ...
        'FontColor', [1, 1, 1], ...
        'HorizontalAlignment', 'center');
end

uilabel(leftPanel, 'Text', 'Shooting % (FG, 3P, 3PA, 2P, FT)', ...
    'Position', [15, leftPanel.Position(4)-275, 370, 16], ...
    'FontSize', 11, 'FontColor', [0.75, 0.75, 0.85]);

shootLabels  = {'FG%', '3P%', '3PA', '2P%', 'FT%'};
shootDefaults = [54.0, 41.0, 5.1, 62.0, 75.0];
shootFields  = cell(1, 5);

for i = 1:5
    x = 15 + (i-1) * (colW + colGap);
    y = leftPanel.Position(4) - 315;
    uilabel(leftPanel, 'Text', shootLabels{i}, ...
        'Position', [x, y+32, colW, 14], ...
        'FontSize', 9, 'FontWeight', 'bold', ...
        'FontColor', [0.6, 0.6, 0.75], ...
        'HorizontalAlignment', 'center');
    shootFields{i} = uieditfield(leftPanel, 'numeric', ...
        'Position', [x, y, colW, 32], ...
        'Value', shootDefaults(i), ...
        'FontSize', 12, ...
        'BackgroundColor', [0.10, 0.14, 0.26], ...
        'FontColor', [1, 1, 1], ...
        'HorizontalAlignment', 'center');
end

findBtn = uibutton(leftPanel, ...
    'Text', 'Find my 90s twin', ...
    'Position', [15, 20, 370, 42], ...
    'FontSize', 14, 'FontWeight', 'bold', ...
    'BackgroundColor', [0.92, 0.27, 0.38], ...
    'FontColor', [1, 1, 1], ...
    'ButtonPushedFcn', @(~,~) runSearch());

%% RIGHT PANEL — results
rightPanel = uipanel(win, ...
    'Position', [430, 15, W-445, H-80], ...
    'BackgroundColor', [0.16, 0.16, 0.24], ...
    'BorderType', 'line', ...
    'BorderWidth', 1, ...
    'HighlightColor', [0.25, 0.25, 0.38]);

uilabel(rightPanel, ...
    'Text', 'RESULTS', ...
    'Position', [15, rightPanel.Position(4)-35, 200, 20], ...
    'FontSize', 10, 'FontWeight', 'bold', ...
    'FontColor', [0.92, 0.27, 0.38]);

bfLabel = uilabel(rightPanel, ...
    'Text', '—', ...
    'Position', [15, rightPanel.Position(4)-65, 370, 20], ...
    'FontSize', 11, 'FontColor', [0.5, 0.9, 0.6]);

uilabel(rightPanel, 'Text', 'Predicted position', ...
    'Position', [15, rightPanel.Position(4)-100, 200, 16], ...
    'FontSize', 11, 'FontColor', [0.75, 0.75, 0.85]);

posLabel = uilabel(rightPanel, ...
    'Text', '—', ...
    'Position', [15, rightPanel.Position(4)-122, 370, 20], ...
    'FontSize', 13, 'FontWeight', 'bold', ...
    'FontColor', [0.76, 0.65, 1.0]);

uilabel(rightPanel, 'Text', 'Profile tags', ...
    'Position', [15, rightPanel.Position(4)-155, 200, 16], ...
    'FontSize', 11, 'FontColor', [0.75, 0.75, 0.85]);

tagsLabel = uilabel(rightPanel, ...
    'Text', '—', ...
    'Position', [15, rightPanel.Position(4)-200, 370, 44], ...
    'FontSize', 10, 'FontColor', [0.6, 0.7, 0.85], ...
    'WordWrap', 'on');

uilabel(rightPanel, 'Text', 'Top 90s matches', ...
    'Position', [15, rightPanel.Position(4)-250, 200, 16], ...
    'FontSize', 11, 'FontColor', [0.75, 0.75, 0.85]);

matchLabels = cell(3, 1);
simLabels   = cell(3, 1);
matchY = [rightPanel.Position(4)-285, rightPanel.Position(4)-335, rightPanel.Position(4)-385];

for i = 1:3
    bg = uipanel(rightPanel, ...
        'Position', [15, matchY(i)-10, 370, 48], ...
        'BackgroundColor', [0.10, 0.14, 0.26], ...
        'BorderType', 'none');
    uilabel(bg, 'Text', string(i), ...
        'Position', [10, 14, 20, 22], ...
        'FontSize', 16, 'FontWeight', 'bold', ...
        'FontColor', [0.92, 0.27, 0.38]);
    matchLabels{i} = uilabel(bg, 'Text', '—', ...
        'Position', [38, 6, 240, 38], ...
        'FontSize', 12, 'FontColor', [1, 1, 1], ...
        'WordWrap', 'on');
    simLabels{i} = uilabel(bg, 'Text', '', ...
        'Position', [290, 14, 65, 22], ...
        'FontSize', 12, 'FontWeight', 'bold', ...
        'FontColor', [0.92, 0.27, 0.38], ...
        'HorizontalAlignment', 'right');
end

%% NESTED SEARCH FUNCTION
    function runSearch()
        findBtn.Enable = 'off';
        findBtn.Text   = 'Searching...';
        drawnow;

        try
            name  = nameField.Value;
            year  = yearField.Value;
            team  = teamField.Value;
            stats = [statFields{1}.Value,  statFields{2}.Value, ...
                     statFields{3}.Value,  statFields{4}.Value, ...
                     statFields{5}.Value,  shootFields{1}.Value, ...
                     shootFields{2}.Value, shootFields{3}.Value, ...
                     shootFields{4}.Value, shootFields{5}.Value];

            result = NBA_main(name, year, team, stats);

            if result.inDataset
                bfLabel.Text      = '   Player already in 90s dataset';
                bfLabel.FontColor = [1.0, 0.7, 0.2];
                posLabel.Text     = '—';
                tagsLabel.Text    = '—';
                for j = 1:3
                    matchLabels{j}.Text = '—';
                    simLabels{j}.Text   = '';
                end
            else
                bfLabel.Text      = 'Not in 90s dataset';
                bfLabel.FontColor = [0.5, 0.9, 0.6];
                posLabel.Text     = result.position;
                tagsLabel.Text    = strjoin(result.tags, '  ·  ');

                for j = 1:min(3, height(result.matches))
                    row = result.matches(j, :);
                    matchLabels{j}.Text = sprintf('%s\n%d  ·  %s  ·  %s', ...
                        row.Player{1}, row.Year, row.Team, row.Position);
                    simLabels{j}.Text   = sprintf('%.0f%%', row.Similarity);
                end
            end

        catch e
            bfLabel.Text      = ['Error: ' e.message];
            bfLabel.FontColor = [1, 0.4, 0.4];
        end

        findBtn.Enable = 'on';
        findBtn.Text   = '  Find my 90s twin';
    end

end